In [15]:
import os
print(os.getcwd())  # shows where Python is looking

C:\Users\KEYRUN\anaconda_projects\db

In [2]:
import pandas as pd
df=pd.read_csv("customer_behaviour.csv")

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,53,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.126754,Yes,Express,Yes,Yes,13,Venmo,Fortnightly
1,2,20,Male,Sweater,Clothing,66,Maine,L,Maroon,Winter,3.069513,Yes,Express,Yes,Yes,1,Cash,Fortnightly
2,3,51,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.047315,Yes,Free Shipping,Yes,Yes,24,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,88,Rhode Island,M,Maroon,Spring,3.475450,Yes,Next Day Air,Yes,Yes,50,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,51,Oregon,M,Turquoise,Spring,2.814874,Yes,Free Shipping,Yes,Yes,32,PayPal,Annually

In [4]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,50000.000000,50000.000000,50000,50000,50000,50000.00000,50000,50000,50000,50000,49527.000000,50000,50000,50000,50000,50000.000000,50000,50000
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,33946,2209,22249,NaN,1221,22531,2282,12798,NaN,36500,8626,28506,28506,NaN,8699,7512
mean,25000.500000,44.077540,NaN,NaN,NaN,59.77438,NaN,NaN,NaN,NaN,3.750284,NaN,NaN,NaN,NaN,25.352060,NaN,NaN
std,14433.901067,15.278395,NaN,NaN,NaN,23.72009,NaN,NaN,NaN,NaN,0.722597,NaN,NaN,NaN,NaN,14.501771,NaN,NaN
min,1.000000,16.000000,NaN,NaN,NaN,18.00000,NaN,NaN,NaN,NaN,2.203543,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,12500.750000,31.000000,NaN,NaN,NaN,39.00000,NaN,NaN,NaN,NaN,3.131605,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,25000.500000,44.000000,NaN,NaN,NaN,60.00000,NaN,NaN,NaN,NaN,3.752282,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,37500.250000,57.000000,NaN,NaN,NaN,80.00000,NaN,NaN,NaN,NaN,4.367013,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,50000.000000,72.000000,NaN,NaN,NaN,102.00000,NaN,NaN,NaN,NaN,5.308792,NaN,NaN,NaN,NaN,52.000000,NaN,NaN

In [5]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating             473
Subscription Status         0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [6]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

-------------------------     CREATE AGE GROUP COLUMN   -------------

In [10]:
labels = ['Young Adult','Adult','Middle-aged','senior']
df['age_group'] = pd.qcut(df['age'],q=4, labels = labels)

In [11]:
df[['age','age_group']].head(10)

   age    age_group
0   53  Middle-aged
1   20  Young Adult
2   51  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   48  Middle-aged
6   61       senior
7   28  Young Adult
8   25  Young Adult
9   55  Middle-aged

--------------------------    CREATE PURCHASE_FREQUENCY_DAYS   --------------------

In [12]:
frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly': 7,
    'monthly' : 30,
    'Quarterly' : 90,
    'Bi-weekly' : 14,
    'Annually' :365,
    'Every 3 months' :90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [13]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [14]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [15]:
df =df.drop('promo_code_used',axis=1)

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [17]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\keyrun\appdata\roaming\python\python313\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [24]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="Admin@123",    
    host="localhost",
    port=5432,
    database="customer_behaviour"
)

engine = create_engine(url)


table_name = "customer"

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "customer_behavior" does not exist

(Background on this error at: https://sqlalche.me/e/20/e3q8)